name: bangzhang_task

on:
  push:
  schedule:
    - cron: '00 15 * * *'
    - cron: '00 22 * * *'


jobs:
  build:
    name: bangzhang_task
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Run a one-line script
      run: echo Hello, world!
        
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
        
    - name: 'Install NPM dependencies'
      run: 
        npm install
        
    - name: Run
      run: npm start
      env:
        DAILY_URL: ${{ secrets.DAILY_URL }}  
        SEND_MAIL: ${{ secrets.SEND_MAIL }}  
        SEND_PASSWORD: ${{ secrets.SEND_PASSWORD }}  
        TO_MAIL: ${{ secrets.TO_MAIL }}  

    
